name: elm-env
channels:
 - conda-forge # essential for rasterio on osx
dependencies:
 - python=3.5
 - bokeh
 - dask
 - datashader
 - distributed
 - gdal=2
 - h5py
 - jupyter
 - krb5
 - matplotlib
 - netcdf4
 - networkx
 - numba
 - numpy
 - pandas
 - pyproj
 - pytest
 - rasterio
 - requests
 - scikit-image
 - scikit-learn
 - scipy
 - shapely
 - statsmodels
 - tblib
 - xarray
 - yaml
 - pip:
   - deap==1.0.1
   - graphviz
   - pysptools
   - pypandoc
   - geopy
   - descartes
   - zict