int_fields_specs:
 - {
    name: DASK_THREADS,
    required: False
  }
 - {
  name: DASK_PROCESSES,
  required: False
  }
str_fields_specs:
 - {name: DASK_EXECUTOR,
    default: SERIAL,
    required: False,
    choices: [
    DISTRIBUTED,
    SERIAL,
    THREAD_POOL,
    PROCESS_POOL]
   }
 - {name: DASK_SCHEDULER,
    required: True
   }
 - {name: LADSWEB_LOCAL_CACHE,
    required: True}
 - {name: HASHED_ARGS_CACHE,
    default: ~/.elm_hashed_args,
    required: True}
 - {name: ELM_EXAMPLE_DATA_PATH,
    required: False}