int_fields_specs:
 - {
    name: DASK_THREADS,
    required: False
  }
 - {
  name: DASK_PROCESSES,
  required: False
  }
 - {
  name: MAX_PARAM_RETRIES,
  required: False
}
str_fields_specs:
 - {name: DASK_EXECUTOR,
    default: SERIAL,
    required: False,
    choices: [
    DISTRIBUTED,
    SERIAL,
    THREAD_POOL,
    PROCESS_POOL]}
 - {name: DASK_SCHEDULER,
    required: True}
 - {name: LADSWEB_LOCAL_CACHE,  # needs to be deprecated
    required: False}
 - {name: HASHED_ARGS_CACHE,    # needs to be deprecated
    default: ~/.elm_hashed_args,
    required: False,
    expanduser: True}
 - {name: ELM_EXAMPLE_DATA_PATH,
    default: ~/elm-data,
    required: False,
    expanduser: True}
 - {name: ELM_TRAIN_PATH,
    default: ~/elm-train-path,
    required: True,
    expanduser: True}
 - {name: ELM_TRANSFORM_PATH,
    default: ~/elm-transform-path,
    required: True,
    expanduser: True}
 - {name: ELM_PREDICT_PATH,
    default: ~/elm-predict-path,
    required: True,
    expanduser: True}
 - {name: ELM_LOGGING_LEVEL,
    default: INFO,
    choices: [INFO, DEBUG]}

